### ISSUE TITLE
just to say thank you

### ISSUE THREAD

**Issue by ekswathi** [ozikazina/Hydra#1]
Hello Bro, thank you for sharing this amazing tool. It is working with blender 3.6 perfectly. But blender 4 is not. It give an error like "no attribute hydra".
I am sharing it in blender artists. I hope you don't mind. 
Is there any chance to convert it to nodes?
And good luck with the thesis.

**Comment by ozikazina** [comment]
Hi there. Thank you very much!
Blender 4.0 seems to have changed something about objects and scenes, as even LuxCore throws a similar exception. I should also warn you that this project is a complete mess under the hood and it's a miracle it even worked, but I'll see what I can do.
Converting it to nodes shouldn't be too difficult, as it would just be a displacement node. The erosion itself is calculated in OpenGL shaders. I'm hoping to also add a better erosion algorithm and CUDA support at the end of this semester.

**Comment by ozikazina** [comment]
It should hopefully be fixed now. Blender 4.0 added AMD's Hydra renderer, which caused a name conflict for Scene data.

**Comment by ekswathi** [comment]
You are too fast. This is really nice work it is going to help me a lot.
Thanks again.
