### ISSUE TITLE
Hydra doesn't work with Wayland protocol

### ISSUE THREAD

**Issue by llleeexxxoooppp** [ozikazina/Hydra#9]
After installing v1.0.1 and v1.1.0 Hydra at 4.3.0a, 4.2.0, 4.1.0, 4.0.2 and 3.6.2lts blender versions with installing moderngl from extension settings and manually after-installing moderngl-5.10.0 with console, every time trying use it like press any button related to settings panel, i receiving something that:

```
Python: Traceback (most recent call last):
  File "/home/archy/.config/blender/4.3/scripts/addons/Hydra/addon/ops_common.py", line 64, in invoke
    erosion_particle.erode(target)
  File "/home/archy/.config/blender/4.3/scripts/addons/Hydra/sim/erosion_particle.py", line 26, in erode
    heightmap.prepare_heightmap(obj)
  File "/home/archy/.config/blender/4.3/scripts/addons/Hydra/sim/heightmap.py", line 113, in prepare_heightmap
    txt = generate_heightmap(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archy/.config/blender/4.3/scripts/addons/Hydra/sim/heightmap.py", line 47, in generate_heightmap
    vao = model.create_vao(ctx, data.programs["heightmap"], vertices=verts, indices=inds)
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'heightmap'
```

At first i tried install moderngl from extension settings panel, and it said that installing was successful and blender need to be restarted, but after restarting, hydra noting that moderngl not installed, I checked through the terminal whether the module was installed, and yes, it was installed at /ver_blender/python/lib/python3.11(or pyton3.10)/site-packages/ had 3 directory related to moderngl, btw in blender has appear Hydra panel but result above, i tried reinstall moderngl manually with 
./python3.11(3.10) -m pip uninstall moderngl in directory with bin python but without result

I tried many version as wrote to be sure, cause previously (several month ago) i used 1.0.1 at some 4.* version blender, and i remember that had some issue and i fixed them with manually install moderngl, but this time i cant fix that
 
My system is linux arch and i dont know what i doing(

**Comment by ozikazina** [comment]
Hello, that is quite odd.
The heightmap program gets compiled immediately after launch but it only prints errors to the console. Check there immediately after launching Blender (I don't know where printouts go in Linux Blender) or try `import Hydra; Hydra.opengl.init_context()` in the console panel to see if it throws any exceptions. The shaders used in this addon are tested on Windows, but Linux compilers seem stricter, so it might fail there.
As for moderngl, the addon tests if it's installed by trying to import it. Try using `import moderngl; import glcontext` in the console panel and see what happens.
I hope it's just some GLSL issue because something like Fedora can't use moderngl at all.

**Comment by llleeexxxoooppp** [comment]
I located problem, from debug log:
`Failed to initialize OpenGL context: (detect) glXGetCurrentContext: cannot detect OpenGL context`
 and then i found this issues #https://github.com/moderngl/moderngl/issues/508 #https://github.com/moderngl/moderngl/issues/644 #https://github.com/moderngl/moderngl/issues/650 
then i tried x11 and hydra has starts finding moderngl and works properly now, problem was in wayland, or more certainly with initializing egl libs as i understand

**Comment by ozikazina** [comment]
Nicely done. Could you please describe your solution in more detail so that I can include it in the readme?

**Comment by llleeexxxoooppp** [comment]
Honestly, my knowledge is shallow to understand how things works and give advice but in general, in Linux today there are two protocols, x11 and wayland, x11 is deprecated and everyone is switching to wayland, so, wayland requires egl and as the developer of moderngl wrote in the issues above, to initialize it, need to change the code in your project a little so
moderngl 5.10 can see egl or wait for moderngl 6.0 but still need to correct code. it's only how I understood it 

In the readme you can just clarify that hydra does not work on Linux with wayland

I don't fixed anything, i just log in on x11 session, and on x11 hydra works fine

**Comment by ozikazina** [comment]
Thank you.

**Comment by llleeexxxoooppp** [comment]
I tried an updated src and now all works properly with wayland, Hydra succsessfuly found moderngl and glcontext.
Thank you!

**Comment by ozikazina** [comment]
You're welcome and thank you for finding those moderngl issues. I accidentaly closed this too soon and had to push the update out this morning 😀. I'll also remove the checks for glcontext in v1.1.1, since it's about to become optional anyway.
